[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cptec-model"
authors = [{name = "Framework CPTEC-Model", email = "frameworkcptec@gmail.com"}]
dynamic = ["version", "description"]
